# Generated by Django 4.2.13 on 2026-04-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('author', models.CharField(blank=True, default='Unknown', max_length=255)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('review_count', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('book_url', models.URLField(blank=True, default='', max_length=1024)),
                ('cover_image_url', models.URLField(blank=True, default='', max_length=1024)),
                ('price', models.CharField(blank=True, default='', max_length=50)),
                ('summary', models.TextField(blank=True, default='')),
                ('genre', models.CharField(blank=True, default='', max_length=255)),
                ('sentiment', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'books',
                'ordering': ['-created_at'],
            },
        ),
    ]
